
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ID FLOAT INT CARET POINT LPAREN RPAREN EQUALS\n\tcal :\texpression \n\t\t|\tepsilon\n\t\n\texpression :\tINT\n\t\t\t\t|\tFLOAT\n\t\t\t\t\n\tepsilon : '
    
_lr_action_items = {'INT':([0,],[4,]),'FLOAT':([0,],[5,]),'$end':([0,1,2,3,4,5,],[-5,0,-1,-2,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cal':([0,],[1,]),'expression':([0,],[2,]),'epsilon':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cal","S'",1,None,None,None),
  ('cal -> expression','cal',1,'p_cal','vcparser.py',10),
  ('cal -> epsilon','cal',1,'p_cal','vcparser.py',11),
  ('expression -> INT','expression',1,'p_expression','vcparser.py',18),
  ('expression -> FLOAT','expression',1,'p_expression','vcparser.py',19),
  ('epsilon -> <empty>','epsilon',0,'p_epsilon','vcparser.py',26),
]
