import turtle              
screen = turtle.Screen()     
screen.bgcolor("blue")  
mario = turtle.Turtle()
mario.shape('turtle') 
mario.speed(1)   
mario.forward(150)           
mario.left(90)              
mario.forward(75)
mario.home()   
screen.exitonclick()